/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package presentacion;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.InputMismatchException;
import java.util.List;
import java.util.Scanner;


import negocio.servicios.BibliotecaService;
import negocio.servicios.impl.BibliotecaImpl;
import negocio.vo.Libro;
import negocio.vo.Genero;

import java.lang.ClassNotFoundException;
import java.sql.*;

public class Main {
	
	
	private static BibliotecaService servicio = new BibliotecaImpl(); //objeto del tipo de la interfaz para que el main se pjueda conectar
	
	public static void main(String[] args) {
		int opcion=-1;
		do{
		menu();
		opcion = leerOpcion();
		
		switch (opcion) {
		case 1:
			insertaLibro();
			break;
		case 2:
			eliminaLibro();
			break;
		case 3:
			actualizaLibro();
			break;
		case 4:
			borraCatalogo();
			break;
			
		case 5:
			List<Libro>libros=servicio.listaLibros();
			imprimir (libros);
		break;
	}
		}while(opcion!=0);		
	}
	
	private static void borraCatalogo() {
		
	}

	private static void menu(){
		System.out.println("Elija una de las siguientes opciones");
	
		System.out.println("1. Insercion de libro");
		System.out.println("2. Eliminacion de libro");
		System.out.println("3. Actualización de libro");
		System.out.println("4. Borrado de catalogo");
		System.out.println("5. Lista de libros");
}
	private static int leerOpcion() {
		int retorno=-1;
		Scanner teclado = new Scanner (System.in);
		retorno = teclado.nextInt();
		
		return retorno;
	}
	static String leerLinea() {
		Scanner teclado = new Scanner(System.in);
		return teclado.nextLine();
	}

	private static void eliminaLibro() {
	System.out.println("Introduce el ISBN del libro a eliminar");
	String isbn = leerLinea();
	Libro l = new Libro();
	l.setIsbn(isbn);
	boolean eliminado = servicio.eliminaLibro(l);
	if (eliminado)
		System.out.println("Libro eliminado con exito");
	else
		System.out.println("Fallo al eliminar el libro");
	}
	private static void insertaLibro() {
		String datosLibro=obtenerDatosLibro();
		Libro l = procesaEntrada(datosLibro);
		boolean insertado = servicio.inserta(l);
		if(insertado) 
			System.out.println("Libro insertado con exito");
		else
			System.out.println("Se detectaron errores al insertar el libro");
		
	}
	
	private static void actualizaLibro() {
		System.out.println("Introduce el ISBN del libro a actualizar");
		String isbn = leerLinea();
		System.out.println("Introduce los nuevos datos para el libro");
		String datosLibro = obtenerDatosLibro();
		Libro l = procesaEntrada(datosLibro);
		boolean actualizado=servicio.actualizaLibro(l, isbn);
		if (actualizado)
			System.out.println("Libro actualizado con exito");
		else
			System.out.println("Fallo al actualizar el libro");
		
	}


	

	private static String obtenerDatosLibro() {
		String datos = null;

		boolean validado = false;
		while (!validado) {
			System.out.println("Introduce los datos de un libro.");
			System.out.println("Usa el formato \"titulo:isbn:genero:autor:paginas\"");
			try {
				datos = leerLinea();
				if (true)// Supongo de momento que valida siempre. Hay que comprobar que tenga el formato
							// deseado
					validado = true;
			} catch (InputMismatchException e) {
				System.out.println("Datos de entrada no v�lidos");
			}
		}

		return datos;
	
	}

	private static Libro procesaEntrada(String datosLibro) {
		Libro libro = new Libro();

		String[] datos = datosLibro.split(":");

		String titulo = datos[0]; 
		String isbn = datos[1];
		Genero genero = Genero.getGenero(datos[2]);
		String autor = datos[3];
		Integer paginas = Integer.parseInt(datos[4]);

		libro.setTitulo(titulo);
		libro.setAutor(autor);
		libro.setIsbn(isbn);
		libro.setGenero(genero);
		libro.setAutor(autor);
		libro.setPaginas(paginas);

		System.out.println(libro);
		return libro;
	}

	private static void imprimir(List<Libro>libros) {
		String format = "%-10s %-30s %-10s %-20s %-4s %n";
		String linesp = "--------------------------------";
		System.out.printf(format, "ISBN", "TITULO", "GENERO", "AUTOR", "PAGINAS");
		System.out.println(linesp);
		for (Libro libro : libros) {

			System.out.printf(format, libro.getTitulo(),
					libro.getIsbn(),
					libro.getGenero(),
					libro.getAutor(), 
					libro.getPaginas());
			System.out.println(linesp);
			
		}
	}
}
